version: '3.8'

networks:
  my-network:

volumes:
  mosquitto-data:
  mosquitto-log:
  mosquitto.conf:
    external: true
    name: mosquitto.conf


services:
  python-sensor:
    image: python-sensor-image:1
    container_name: python-sensor-container
    #restart: always
    depends_on:
      - mqtt
    networks:
      - my-network
    environment:
      BROKER_ADDRESS: my-mqtt-broker
      BROKER_PORT: 1883

  analytics:
    image: analytics-image:1
    container_name: analytics-container
    #restart: always
    depends_on:
      - mqtt
    networks:
      - my-network
    environment:
       BROKER_ADDRESS: my-mqtt-broker
       BROKER_PORT: 1883

  eventinfo:
    image: eventinfo-image:1
    container_name: eventinfo-container
    #restart: always
    depends_on:
      - analytics
      - mqtt
    ports:
      - "3000:3000"
    networks:
      - my-network
    environment:
      BROKER_ADDRESS: my-mqtt-broker
      BROKER_PORT: 1883

  mqtt:
    image: eclipse-mosquitto:2
    container_name: my-mqtt-broker
    volumes:
      - mosquitto.conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - my-network
    ports:
      - "1883:1883"
